version: "3"
services:
  postgresql:
    image: postgres:16.1
    container_name: postgres_db
    environment:
      POSTGRES_DB: fila-do-barbeiro-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
